/* C:\BORLANDC\INCLUDE\WINCOMP.H 4/29/1992 23:40*/
#define  IDM_ABRIR	1
#define  IDM_VER	2
#define  IDM_COMPILAR	3
#define  IDM_DEPURAR	4
#define  IDM_ACERCA	5
#define  IDM_SALIR	6
#define  IDM_AYUDA	7
#define  IDM_VERFUENTE	8
#define  IDM_VERCOMPIL	9

#define  IDC_OK	        10
#define  IDC_CANCELAR	11
#define  IDC_EMPEZAR	12
#define  IDC_INFORME	13
#define  IDC_MAKE	14
#define  IDC_GRUPO	15
#define  IDC_TEXTO1	16
#define  IDC_TEXTO2	17
#define  IDC_EDIT	18
#define  IDC_DIRACT	19
#define  IDC_LISTFICH	20
#define  IDC_LISTDIR	21
#define  IDC_TEXTO3	22
#define  IDC_TEXTO4	23
