/* C:\BORLANDC\INCLUDE\WINRESOL.H 4/25/1992 9:46*/

/* Definiciones para los ID's de los controles */
#define  IDC_TEXTO1     1
#define  IDC_TEXTO2     2
#define  IDC_DIRACT     3
#define  IDC_EDIT       4
#define  IDC_LISTFICH   5
#define  IDC_LISTDIR    6
#define  IDC_OK         7
#define  IDC_CANCELAR   8
#define  IDC_TEXTO3     9
#define  IDC_TEXTO4     10

/* Definiciones para los ID's de los men£s */
#define  IDM_ABRIR     10
#define  IDM_VER       11
#define  IDM_SALIR     12
#define  IDM_RESOLVER  13
#define  IDM_ACERCA    14
#define  IDM_AYUDA     15

#define  BOTONFIN     1    /* ID para los controles de Fin y Abort respect. */
#define  BOTONABORT   2
#define  BARRAPORCENT 3        /* ID para la ventana est tica de porcentaje */

