/* ID's para los tipos de ventana que pueden crearse */
#define  TV_BLOQUES        1
#define  TV_ESQUEMA        2
#define  TV_BIBLIO         3
#define  TV_METAFILE       4

/* ID's para los Items de los diferentes men£s */
#define  IDM_RESIST        1
#define  IDM_CONDENS       2
#define  IDM_BOBINA        3
#define  IDM_TRANSIS       4
#define  IDM_DIODOS        5
#define  IDM_GENVDEPV      6
#define  IDM_GENVDEPI      7
#define  IDM_GENIDEPV      8
#define  IDM_GENIDEPI      9
#define  IDM_GENV          10
#define  IDM_GENI          11
#define  IDM_BATERIA       12
#define  IDM_CABLE         13
#define  IDM_NUDO          14
#define  IDM_MASA          15
#define  IDM_CUAD          16
#define  IDM_VOLT          17
#define  IDM_AMPER         18
#define  IDM_OBJETO        19
#define  IDM_GRUPO         20
#define  IDM_MOVER         21
#define  IDM_DESPLAZ       22
#define  IDM_OTRO          23
#define  IDM_LEER          24
#define  IDM_GRANDE        25
#define  IDM_PEQUENO       26
#define  IDM_EMPEZAR       27
#define  IDM_TERMINAR      28
#define  IDM_ABRIR         29
#define  IDM_GUARDAR       30
#define  IDM_BIPOLAR       31
#define  IDM_JFET          32
#define  IDM_MOSFET        33
#define  IDM_ACERCA        34
#define  IDM_HORIZ         35
#define  IDM_VERT          36
#define  IDM_ESPEJO        37
#define  IDM_REJILLA       38
#define  IDM_PUNTERO       39
#define  IDM_DIODO         40
#define  IDM_DIODOZ        41
#define  IDM_DIODOV        42
#define  IDM_ADDSYM        43
#define  IDM_BUSCSYM       45
#define  IDM_LISTSYM       46
#define  IDM_CREABIBL      47
#define  IDM_SUPRBIBL      48
#define  IDM_IMPRIMIR      50
#define  IDM_ANTERIOR      51
#define  IDM_SIGUIENTE     52
#define  IDM_MOSAICO       53
#define  IDM_CASCADA       54
#define  IDM_INDICE        55
#define  IDM_GUARDARCOMO   56
#define  IDM_CERRAR        57
#define  IDM_RECOLOCAR     58
#define  IDM_TEXTO         59
#define  IDM_PUERTO        60
#define  IDM_BLOQUE        61
#define  IDM_PRIMERESQUEMA 62

/* Tama¤o de Scroll y de Rejilla en pixels */
#define  SCRLDESPL      5
#define  TAMREJ         5

/* ID's para los controles de las cajas de di logo */
#define  IDC_TEXTO1     1
#define  IDC_TEXTO2     2
#define  IDC_DIRACT     3
#define  IDC_EDIT       4
#define  IDC_LISTFICH   5
#define  IDC_LISTDIR    6
#define  IDC_OK         7
#define  IDC_CANCELAR   8
#define  IDC_EDIT2      9
#define  IDC_ICONO     10
#define  IDC_HORIZ     11
#define  IDC_VERT      12
#define  IDC_ESPEJO    13
#define  IDC_MAS       14
#define  IDC_BITMAP    15
#define  IDC_EDITBASE  40
#define  IDC_TEXTBASE  60
#define  IDC_COMBO1    80
#define  IDC_COMBO2    81
#define  IDC_BOTON1    82
#define  IDC_BOTON2    83
#define  IDC_BOTON3    84
#define  IDC_BOTON4    85
#define  IDC_SCROLL    86
#define  IDC_Ti        87
#define  IDC_Tr        88
#define  IDC_Tf        89
#define  IDC_To        90
#define  IDC_BOTONBASE 91

/* ID's para los distintos elementos */
#define  RESISTENCIA    1
#define  CONDENSADOR    2
#define  BOBINA         3
#define  TRANSISTOR_BP  4
#define  TRANSISTOR_BN  5
#define  TRANSISTOR_JP  6
#define  TRANSISTOR_JN  7
#define  TRANSISTOR_MP  8
#define  TRANSISTOR_MN  9
#define  DIODO          10
#define  DIODOZ         11
#define  DIODOV         12
#define  BATERIA        13
#define  GENV           14
#define  GENI           15
#define  GENVDEPV       16
#define  GENVDEPI       17
#define  GENIDEPV       18
#define  GENIDEPI       19
#define  VOLTIMETRO     20
#define  AMPERIMETRO    21
#define  METAFILE       22

/* Posici¢n del submen£ "Ventana" dentro del men£ de esquema */
#define  BLOQUES_SUBMENU_POS  4
#define  ESQUEMA_SUBMENU_POS  5
#define  BIBLIO_SUBMENU_POS   2

/* Tama¤o por defecto de los MetaFiles */
#define  MF_TAMHORZ     200
#define  MF_TAMVERT     200

/* Tama¤o por defecto de los puertos */
#define  TAMHPORT       25
#define  TAMVPORT       14
