/* C:\BORLANDC\INCLUDE\WINGRAF.H 5/11/1992 13:29*/
#define  IDM_ABRIR	1
#define  IDM_VER	2
#define  IDM_SALIR	3
#define  IDM_TRAZAR	4
#define  IDM_AYUDA	5
#define  IDM_ACERCA	6
#define  IDM_PARAMETROS	7
#define  IDM_ESCALAS	8
#define  IDM_COLORES	9
#define  IDM_DERIVAR	10
#define  IDM_INTEGRAR	11
#define  IDM_TIEMPO	12
#define  IDM_FRECUENCIA	13
#define  IDM_GRANDE     14
#define  IDM_PEQUENO    15

#define  PTRABAJO	0
#define  TIEMPO	        1
#define  FRECUENCIA	2
#define  FOURIER	3
#define  SENSIBILIDAD	4

#define  DIRECTA 	0
#define  INVERSA 	1

#define  INC 		0.02

#define  SCRLDESPL	5

#define  IDC_OK		10
#define  IDC_CANCELAR	11
#define  IDC_EMPEZAR	12
#define  IDC_GRUPO	13
#define  IDC_GRAFICA	14
#define  IDC_TABLA	15
#define  IDC_TEXTO1	16
#define  IDC_TEXTO2	17
#define  IDC_EDIT	18
#define  IDC_DIRACT	19
#define  IDC_LISTFICH	20
#define  IDC_LISTDIR	21
#define  IDC_TEXTO3	22
#define  IDC_TEXTO4	23
#define  IDC_DOMINIO	24
#define  IDC_PTRABAJO	25
#define  IDC_TIEMPO	26
#define  IDC_FRECUENCIA	27
#define  IDC_FOURIER	28
#define  IDC_SENSIBILIDAD	29
#define  IDC_EDIT2	30
#define  IDC_TRACKING	31
#define  IDC_COORDS	32
#define  IDC_SCRLX	33
#define  IDC_SCRLY	34
#define  IDC_COLORESC	35
#define  IDC_COLORGRF	52
#define  IDC_MULT       69
#define  IDC_DIV        70
#define  IDC_POR2       71
#define  IDC_POR10      72
